### PR TITLE
Fix Slider Return Values, Add Slider Step Support

### PR DESCRIPTION
**Pull request by Patrick-Seymour**
This started with a look at the "MCM Slider Subtracts 1" issue that was previously closed. I noticed this myself, and wanted to address the issue for my own mod so that I could have better, easier return values from MCM, and add in stepping support. I found a couple of bugs with the vanilla XCOM2 implementation of the sliders, and made some fixes and changes.

Short vid of changes in action: https://youtu.be/r_lAvgWAym0

Commit Summary

= Slider display value matches return value when displaying an integer and typecasting to integer.
= Floating point values can be utilized by the slider.
= The slider can be "stepped" (not supported by UISlider, done entirely in the MCM codebase).
= The slider can use 0-100% instead of just 1-100% (apparently a fix for a different UISlider bug/issue).
= The slider no longer bugs out when setting the step size (UISlider had a bug in it).
= Added a GetBounds() function to the slider API, implemented in both Slider and SliderFacade.
= Added Debug configuration so that I could use a debugger on it. I think it's necessary, anyways. Not too sure now that I think about it, I never did test without a Debug build. Doesn't really hurt to leave it in there I suppose.

The only thing that is technically "breaking" about this commit (other than stopping MCM from rounding its values, which I consider more of a bug fix than anything else) is that MCM will display decimals unless used with a step value of 1. It doesn't change its behavior, and the return value from MCM is still in decimal floats as it always has been. But if someone specifically wants only integers they can simply specify a step value of 1, and MCM will adjust its return value accordingly so you know it's working. If they've been doing that up to this point, then they will see no change (as the step property of sliders wasn't doing anything before this commit).

I like this way of doing things because it covers the most likely use-case scenarios without requiring any special considerations. Someone is unlikely to want to display integers but record floats, and if they do they can just add in a custom display filter function and assign it to the slider control as it was originally designed, to extend its functionality.

I have (much) longer ramblings about these changes if you want to hear them, but here's short expansions on a couple of the changes.

= Since the slider displays an integer, typecasting its return type to an integer should result in the same value. A modder shouldn't need to worry about integer truncation, that's why it's standardized. Right now I have the slider not rounding the integer result, though if it is desired in order to give the value scrolling a more smoother, even approach, it should adjust the return value to match the display value. Really the only changes necessary to do this is something like the following. I didn't test this, but it should make the slider display and return the same value.

GetSliderPositionFromValue(): add in a `-PercentPerStep()/2.0` to the percent after calculating the return statement
GetSliderValueFromPosition(): add in a `+PercentPerStep()/2.0` to the percent before calculating the return statement

= UISlider SetStepSize() broke the slider control if called. It's actually coded to call the same function as SetPercent(), but only for the flash control instead of the UC code. This results in the UC storing a value and the flash control storing a percent, but these two not aligning properly. It fixes itself when touched or SetPercent() is called again. I've fixed this in the MCM_XCOM2_UISlider replacement class. MCM spawns this class instead of the UISlider core class, because I needed to override class functions for it.

= UISlider has a range of 1% to 100%, for no reason. If you change it to 0%, you get buggy behavior in the slider but this was easily rectifiable. The problem was UC's default percent was 0, and if this value doesn't change then SetPercent() optimizes away the call to the flash control to change its value. So, the flash control never gets called to initialize itself, even to zero. I bet this is why they put in a 1 here as the minimum value, to "force" this call to the flash control to set itself on initialization, instead of making a flag "HasThisFlashControlBeenInitializedYet".

= Also regarding SetStepSize(), it doesn't do what it says on the tin. "Steps" in its context is just how much of the slider bar moves when you click the left and right arrow buttons on it, NOT "only display/return values that are in increments of steps". See: OnIncrease() and OnDecrease(). I was hoping that dropdowns would function in a similar way, but unfortunately they don't. Dropdowns suck in XCOM2 because if you have a large number of options, you cannot select some of them because attempting to scroll 1px on the dropdown moves the entire list by something like 10%, and it's not configurable. Flash is doing the scrolling, and we can barely interact with flash elements. What we really need to fix these scrolling issues is someone to find and decompile the flash UI components, so any methods of use on those components can be identified.

### CODE REVIEW

**Comment by andrewgu** [comment]
Awesome work and sweet submission! I agree with your points about ideal number handling behavior for the slider. 

I will test it on my own PC and if things work as described, I will merge and update the mod.

**Comment by BlueRaja** [comment]
Any update on this?

**Comment by andrewgu** [comment]
I've been out of town for most of the time since this pull request got submitted. I'll probably get the testing done this weekend when I get back. Sorry for the delay!

**Comment by BlueRaja** [comment]
@Patrick-Seymour 
> MCM will display decimals unless used with a step value of 1

Is this possible to change?  I think the correct behavior should be _"MCM will display integers unless one of `min`/`max`/`default`/`step` are non-integer"_ (which you can check with `int(x) == x`)

**Comment by Patrick-Seymour** [comment]
Doesn't really work. What happens when min=0, max=1, default=0, step=0? All integers, but it's not likely that someone will want a Slider to represent what is effectively a boolean value. This use case will almost certainly be decimal. And as someone using the Slider, that step=0 *means* that I want decimal. If I don't, then I'll pass in a different value.

I think it's fine as-is, after all one of the points of this change is to simplify the rules of usage. Having special rules that *assume* integer or decimal usage based on parameters is something that I think should be avoided. As someone who is using MCM, I'd much rather it be explicit: If I want integers, I'll just step=1 the Slider, no confusion or special rules. And if I *do* want to display something different, you've already provided an interface for a custom display function.

Yeah, this might break the display on a mod or two (depending on how many people are using MCM), but in the long run simplicity should rule. Ultimately it is your mod though, your rules.

**Comment by BlueRaja** [comment]
`step=0` would obviously be a special case (it has to be already, since step=0 has no inherent meaning).

I don't see an issue with "assuming integer or decimal" when you can determine with 100% accuracy if the value will be an integer or decimal...

Example: min=0, max=100, default=50, step=10.  This should clearly be displayed as "50", not "50.0". There is no possible way to ever get a decimal here.

_(Also I am not the repo owner, just another MCM user)_

**Comment by andrewgu** [comment]
Still out of town so I haven't been able to play with the compiled mod myself, but probably best to resolve the discussion as soon as possible regardless.

Question for @Patrick-Seymour : If you set an integer step size, will the values that are returned always come back as integer values? I suppose that's tied into the question "can you select float values if step size and other parameters are all integral?" 

If so, then I think we can just automatically omit the forced decimal point in the default "display filter" for when float(int(n)) == n and it would accomplish an intuitive result in the vast majority of cases. For other cases, MCM could just provide some helper functions for different display filters people might want to use.

I'm pretty sure that actual floating point sliders are the minority case, and that integral steps for integral ranges is probably going to be the most common case. Given that, automatic pretty formatting for integer values seems to be the approach with the least side effect to accommodate the most cases without requiring much in the way of special inputs.

**Comment by BlueRaja** [comment]
I attempted to test this fix _(because the broken sliders are preventing me from supporting MCM in my mods)_, but it appears the branch is missing the file `MCM_XCOM2_UISlider.uc`
@Patrick-Seymour ^^^

**Comment by Patrick-Seymour** [comment]
Thanks for pointing that out, added the missing file. Basically just the original UISlider but it properly initializes itself when the starting value is zero, and it no longer messes up the slider when attempting to change the step size.

**Comment by BlueRaja** [comment]
Just tried it out - it works fantastic!  Looks ready to merge to me.

Interestingly, even with step=5, the value didn't display a decimal-point - nice!

**Comment by Patrick-Seymour** [comment]
Change min=0.5 and step=5 and it will display 0.5, 5.5, 10.5, etc. It just displays decimals when necessary. (It uses the min value to determine where to step from: A slider with min=0.5 max=10 step=1 will step from 9.5 to 10 at the slider's max position.)

Even on a 0-1 slider it will just display "1" at the slider's max position. There could potentially be special logic for making the display be more consistent with the number of decimal digits being displayed (special logic depending on min/max/step), but that seems to introduce too much complexity and honestly, I don't think people will care as long as it works.

**Comment by BlueRaja** [comment]
Yes, that behavior is fine :+1:.  I thought you were saying my above case would display eg. "125.0" even though the number is always a multiple of 5.

**Comment by BlueRaja** [comment]
Super excited to get this merged :D I added MCM support to most of my mods over the past week, but most of them have sliders so I'm waiting for this fix to update them.

@andrewgu let me know if you need any help testing or anything.

**Comment by andrewgu** [comment]
Yup! I've cleared out my morning tomorrow to test, merge, and deploy. Should be smooth, I just need to do it.

**Comment by andrewgu** [comment]
@Patrick-Seymour @BlueRaja Do you guys know what happens if the interface files are out of sync with the version compiled in the client mod? Asking because this pull request adds GetBounds to MCM_API_Slider.uc, which will bring it out of sync with any mods that don't update and recompile.

If it's non-breaking, then no big deal. If it's breaking, I'm going to version it into a new minor API version.

**Comment by andrewgu** [comment]
Confirmed that the additional API call doesn't seem to introduce any issues.

**Comment by Patrick-Seymour** [comment]
Ran tests comparing a mod compiled against different MCM-API interface versions, crossed with different MCM implementation versions:

Mod-GetBounds MCM-GetBounds: works fine (desired result)
Mod+GetBounds MCM-GetBounds: crashes (expected result)
Mod+GetBounds MCM+GetBounds: works fine (expected result)
Mod-GetBounds MCM+GetBounds: works fine (desired result)

Also did a test of Mod-GetBounds MCM+GetBounds that calls SetBounds (defined after GetBounds) just to make sure that there's no issues with function pointers or anything like that, and it seemed to work fine (desired result).

Seems to me that adding functions to an interface doesn't cause issues.

**Comment by BlueRaja** [comment]
It would still be breaking if a mod depended on it and the latest MCM wasn't installed _(eg. if it's installed through Nexus)_, right?

**Comment by andrewgu** [comment]
@BlueRaja There shouldn't be an issue if MCM is missing completely because the MCM_API_Register macro will fail out on its check for MCM. Unless the mod is trying to hook into MCM directly instead of using the macro, there shouldn't be any issues.

**Comment by BlueRaja** [comment]
No, I mean if MCM is installed but it's an older version that doesn't contain `GetBounds`

**Comment by Patrick-Seymour** [comment]
BlueRaja's right, in such a situation where the mod calls GetBounds it would crash because the installed MCM wouldn't be implementing it, on Nexus (theoretically on Workshop it will have updated already). Maybe if there is a way to query the major/minor version of the installed MCM instance, the mod could decide that since it needs GetBounds added in v1.2, if the installed version of MCM is v1.1 then fail the instantiation itself? Dunno, I haven't thought about any sort of compatibility stuff. And in fact, I personally don't need GetBounds, I just thought it should be added because there was no way to retrieve the bounds of the slider, even though there were similar functions for the rest of the slider data. Can always just remove it if it's a headache.

**Comment by andrewgu** [comment]
@BlueRaja Oooooh... yeah good point. That would be an issue.

**Comment by andrewgu** [comment]
@Patrick-Seymour Yeah, based on the forward compatibility issue (more recent mod, less recent MCM version), we would need to handle the addition of GetBounds by creating a "1.2" version of the interface files. I don't think it's worth creating a new minor interface version for just one getter, so I'll take it out of this update and put it back in alongside some other new functionality in the future. I agree that it's a good idea to have the API call in there.

**Comment by andrewgu** [comment]
Tests look good for both this and PR-45, merging.

**Pull request merged**
